FROM ubuntu:16.04

RUN apt-get update && apt-get -y install \
        autoconf \
        automake \
        build-essential \
        cmake \
        git \
        libass-dev \
        libfreetype6-dev \
        libtheora-dev \
        libtool \
        libvorbis-dev \
        mercurial \
        pkg-config \
        texinfo \
        wget \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*
 
